stages:
  - sync
  - build

sync-github:
  stage: sync
  image: alpine:latest
  tags:
    - gitlab-org
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"
    - git remote add github "https://x-access-token:${GITHUB_TOKEN}@github.com/ayaandh/tekst.git"
    - git push github HEAD:main --force

build-linux:
  stage: build
  image: ubuntu:24.04
  tags:
    - gitlab-org
  before_script:
    - apt-get update
    - apt-get install -y cmake g++ make
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --config Release --parallel
    - |
      if [ -f build/bin/Release/tekst ]; then
        cp build/bin/Release/tekst build/tekst
      elif [ -f build/bin/tekst ]; then
        cp build/bin/tekst build/tekst
      else
        echo "tekst was not found"
        exit 1
      fi
    - |
      if [ -f build/bin/Release/tk ]; then
        cp build/bin/Release/tk build/tk
      elif [ -f build/bin/tk ]; then
        cp build/bin/tekst build/tk
      else
        echo "tk was not found"
        exit 1
      fi
  artifacts:
    name: "Tekst-TK-linux"
    paths:
      - build/tekst
      - build/tk
    expire_in: 30 days